AWSTemplateFormatVersion: 2010-09-09
Description: |
  With this template format i want to create a static website that shows some pictures of the baby cats.
Resources:
  Babycatsecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Shortly i write something # Required
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: 80
          ToPort: 80 
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22 
          CidrIp: 0.0.0.0/0               
  Babycats:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds:
        - !Ref Babycatsecgroup
      Tags:
        - Key: Name 
          Value: !Sub Web Server of ${AWS::StackName} Stack 
  
      UserData: 
        Fn::Base64:
          !Sub |
            #! /bin/bash
              yum update -y
              yum install httpd -y
              FOLDER="https://raw.githubusercontent.com/abdullahy47/my-projects/main/projects/Project-101-kittens-carousel-static-website-ec2/static-web"
              cd /var/www/html
              wget $FOLDER/index.html
              wget $FOLDER/cat0.jpg
              wget $FOLDER/cat1.jpg
              wget $FOLDER/cat2.jpg
              wget $FOLDER/cat3.png
              systemctl start httpd
              systemctl enable httpd 
      
Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt Babycats.PublicDnsName
    Description: Kittens Carousel Application URL