AWSTemplateFormatVersion: 2010-09-09
Description: |
  This part consist with the aim of the project
Parameters:
  KeyName:
    Description: Enter the name of your Key Pair for SSH connections
    Type: AWS::EC2::KeyPair::KeyName
  Subnet:
    Description: Select at least 2 subnet
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  romannumsecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: this group created for the roman numerals converter # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref romannumsecgroup
      UserData: !Base64 |
        #!/bin/bash 
        yum update -y
        yum install python3 -y
        pip3 install flask
        cd /home/ec2-user
        wget https://raw.githubusercontent.com/abdullahy47/my-projects/main/Project-001-Roman-Numerals-Converter/app.py
        mkdir templates
        cd templates
        wget https://raw.githubusercontent.com/abdullahy47/my-projects/main/Project-001-Roman-Numerals-Converter/templates/index.html
        wget https://raw.githubusercontent.com/abdullahy47/my-projects/main/Project-001-Roman-Numerals-Converter/templates/result.html
        cd ..
        python3 app.py
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
    Description: Roman Numerals Converter Application URL